### ISSUE TITLE
Flush rewrite rules / 404 for premise-portfolio/ CPT

### ISSUE THREAD

**Issue by francoisjacquet** [PremiseWP/premise-portfolio#1]
@mvallejo3 I have tried to fix the issue in the https://github.com/PremiseWP/premise-portfolio/tree/flush-rewrite-rules-cpt-404 branch without success.
I have followed these instructions: http://solislab.com/blog/plugin-activation-checklist/#flush-rewrite-rules

**Comment by mvallejo3** [comment]
fixed with https://github.com/PremiseWP/premise-portfolio/commit/459600af122ec3afc9a12b40b712da72b03cd709
